### ISSUE TITLE
Adopt semver version

### ISSUE THREAD

**Issue by joaomoreno** [Nifelheimaro/hhtheme#1]
Hi, VS Code developer here. Due to a recent change, the next version of Code will require every extension to have a [semver](http://semver.org/) compatible version. `Hackers Haze Theme` is one of the very few that doesn't have one; its latest version seems to be [1.0.0.2](https://marketplace.visualstudio.com/items/Nuuf.theme-hackershaze).

In order to stay compatible with Code, could you publish a more recent version using a semver compatible version number?

Related to Microsoft/vscode-vsce#55 and Microsoft/vscode#1111

**Comment by stereokai** [comment]
@Nifelheimaro  Hey, I'd really like to try this theme out - would you kindly update it with a semver compatible version number? Otherwise I would have to steal it and re-publish it :)

**Comment by joaomoreno** [comment]
Feel free to do that, @stereokai. This request was created almost 2 months ago and got no reply.

**Comment by stereokai** [comment]
@joaomoreno There's a much easier way to get the theme. Install it, then wait for Code to alert you that the extension is broken. The alert will contain the path to where the theme is installed. Access that location and open .vsixmanifest and package.json. Replace instances of "1.0.0.2" with "1.0.0" or whatever semver compliant number you wish, and restart Code.

You can then proceed with trying out the theme as normal. To be honest, I was quite disappointed, the colors for the different code elements look almost identical :(

**Comment by Nifelheimaro** [comment]
Hello, im sorry for this late response. I recieved the news that it wasn't compatible anymore and forgot about it. I'll get right on it! And ofc you are free to do as you wish it :)

**Comment by Nifelheimaro** [comment]
I have published a new version, sorry for the long wait.

**Comment by stereokai** [comment]
@Nifelheimaro Thanks a lot, and don't worry about it :)
